executor: slurm
jobs: 50
latency-wait: 60
use-conda: true
rerun-incomplete: true
rerun-trigger: mtime
keep-going: false
retries: 3
wrapper-prefix: "file:workflow/wrappers/"

default-resources:
    mem_mb: 8 * 1024
    runtime: 10 * 2 ** (attempt - 1)
max-threads: 8
